# Generated by Django 5.0.7 on 2024-10-08 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0006_alter_user_email'),
        ('quizzes', '0005_quiz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Course_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_value',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
