# Generated by Django 5.0.7 on 2024-10-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0008_alter_grade_quiz_examresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='total_score',
            new_name='total_items',
        ),
    ]
