# Generated by Django 5.1 on 2024-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0009_rename_total_score_examresult_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('final', 'Final')], default='prelim', max_length=7),
        ),
        migrations.AddField(
            model_name='grade',
            name='period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('final', 'Final')], default='prelim', max_length=7),
        ),
    ]
