# Generated by Django 4.2.16 on 2024-10-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0011_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='classification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='transmuted_grade',
            field=models.FloatField(default=0),
        ),
    ]
