# Generated by Django 4.2.16 on 2024-10-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0012_grade_classification_grade_transmuted_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='transmuted_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
