# Generated by Django 5.0.7 on 2024-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_req_score_to_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
