# Generated by Django 5.0.7 on 2024-10-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
