# Generated by Django 5.1 on 2024-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_remove_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('final', 'Final')], default='prelim', max_length=7),
        ),
    ]
