# Generated by Django 5.1 on 2024-10-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(default=1, help_text='Number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Time limit for each attempt in minutes'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='req_score_to_pass',
            field=models.FloatField(help_text='Score to pass'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='Duration of the quiz in minutes'),
        ),
    ]
