# Generated by Django 4.2.16 on 2024-10-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_attempts_allowed_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
